<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            text: "Login"

        TextInput:
            id: user
            hint_text: "Utilizador"

        TextInput:
            id: password
            hint_text: "Password"
            password: True

        Button:
            text: "Entrar"
            on_release:
                root.do_login(user.text, password.text)
